language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

env:
  - ARCH=x86_64
  - ARCH=i686

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose
  - cargo test --verbose
